### ISSUE TITLE
Crash when starting capture on UE 5.2

### ISSUE THREAD

**Issue by JasonShaojiesun** [irajsb/UE_CaptureSubsystem#1]
Whenever I try to start capture, it crashes the editor. The following is the crash log, is there any way to fix this problem? Thanks a lot!!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000001a6000005c5

UnrealEditor_Engine
UnrealEditor_CaptureSubsystem!UCaptureSubsystemDirector::OnBackBufferReady_RenderThread() [D:\UE5Projects\RecordingTest\Plugins\CaptureSubsystem\Source\CaptureSubsystem\Private\CaptureSubsystemDirector.cpp:193]
UnrealEditor_CaptureSubsystem!TBaseUObjectMethodDelegateInstance<0,UCaptureSubsystemDirector,void __cdecl(SWindow &,TRefCountPtr<FRHITexture> const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Program Files\UE_5.2\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:552]
UnrealEditor_SlateRHIRenderer
UnrealEditor_SlateRHIRenderer
UnrealEditor_SlateRHIRenderer
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by JasonShaojiesun** [comment]
Crashes on 5.03 as well

**Comment by irajsb** [comment]
in project settings set viewport client to CaptureGameViewportClient

**Comment by irajsb** [comment]
![image](https://github.com/irajsb/UE_CaptureSubsystem/assets/36444724/2de0dab4-3938-4a4b-9602-c36bfcc74ed6)

**Comment by JasonShaojiesun** [comment]
Problem solved! Lots of thanks!
