### ISSUE TITLE
Crash when starting capture in UE5.2

### ISSUE THREAD

**Issue by Jimmy-Min** [irajsb/UE_CaptureSubsystem#2]
Hi, I add this plugin into my project and set the start capture funtion when the game starts. It will crash and the callstack is below.

LoginId:ee59dbdb47407b5f9a3a199aa4238aae
EpicAccountId:f226dda7fb214bd9b9c0bd4f67d8202e

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000088

avformat_59
avformat_59
avformat_59
UnrealEditor_CaptureSubsystem!UCaptureSubsystemDirector::Create_Video_Encoder() [E:\FProjects\UEProj\Study03\Plugins\UE_CaptureSubsystem\Source\CaptureSubsystem\Private\CaptureSubsystemDirector.cpp:531]
UnrealEditor_CaptureSubsystem!UCaptureSubsystemDirector::CreateEncodeThread() [E:\FProjects\UEProj\Study03\Plugins\UE_CaptureSubsystem\Source\CaptureSubsystem\Private\CaptureSubsystemDirector.cpp:326]
UnrealEditor_CaptureSubsystem!UCaptureSubsystemDirector::OnBackBufferReady_RenderThread() [E:\FProjects\UEProj\Study03\Plugins\UE_CaptureSubsystem\Source\CaptureSubsystem\Private\CaptureSubsystemDirector.cpp:205]
UnrealEditor_CaptureSubsystem!TBaseUObjectMethodDelegateInstance<0,UCaptureSubsystemDirector,void __cdecl(SWindow &,TRefCountPtr<FRHITexture> const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [E:\DevTools\UE5\UE_5.2\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:552]
UnrealEditor_SlateRHIRenderer
UnrealEditor_SlateRHIRenderer
UnrealEditor_SlateRHIRenderer
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32

**Comment by Jimmy-Min** [comment]
Hello author, I found the cause of the crash, it is because I used "Get recommend video file name". If I specify to write to a certain file, then there is no problem, but if I don't specify, it will still crash. Is there anyway to fix? Thank you.

**Comment by irajsb** [comment]
Few things to check

1.  print the result of  Get recommend video file name and see if the path seems to be correct (but don't begin capture so it doesn't crash)
2. See if the game has permission to write at that path 
3. You can make your own file path algorithm ( for example save videos at the project folder )

**Comment by irajsb** [comment]
Based on your country I think there can be a folder name with non English names in the path and that can also cause the crash !

**Comment by Jimmy-Min** [comment]
> Few things to check
> 
> 1. print the result of  Get recommend video file name and see if the path seems to be correct (but don't begin capture so it doesn't crash)
> 2. See if the game has permission to write at that path
> 3. You can make your own file path algorithm ( for example save videos at the project folder )

Thanks，I will check it.

**Comment by Jimmy-Min** [comment]
I found out that the Capture folder must exist in My Documents.
