### ISSUE TITLE
Unsafe game exit

### ISSUE THREAD

**Issue by F1nansist** [irajsb/UE_CaptureSubsystem#6]
When u start recording u should manually stop recording or happened something strange.
For example, someone starts recording and then presses alt+f4 and recording will not stop by itself. In this case created video-file is empty. it is occupied and u cant delete it.

**Comment by irajsb** [comment]
I don't think there is any app that can alt+f4 and exit correctly they just get force interrupted by windows ( Elden ring is only app that prevents that by some method , once you press alt+f4 screen fades to black and saves then exits ) . in case of video encoding  files even if you record for an hour unless you end the file correctly it will not be playable. 
https://forums.unrealengine.com/t/catching-blocking-alt-f4-in-packaged-game/348273

**Comment by F1nansist** [comment]
I tried to stop recording while sub system start deinitializing but file still isnt playable. Looks like is needed to stop recording a litle bit earlier but dont understand where i can do this

**Comment by irajsb** [comment]
Added  to latest version:
```
void UVideoCaptureSubsystem::Deinitialize()
{
	Super::Deinitialize();
	ForceEndCapture();
}
```
Which forces stopping without waiting for remaining of frames since application is force closing
