### ISSUE TITLE
Black rectangle in VR

### ISSUE THREAD

**Issue by F1nansist** [irajsb/UE_CaptureSubsystem#7]
In desktop all is okay but it doesnt capture VR
Im talking about capturing VR from Windows (not mobile version)
Logs are pure, no errors or warnings

**Comment by F1nansist** [comment]
CaptureSubsystemDirector.cpp on 310 line (in VR)
Texture points to '\0'

**Comment by irajsb** [comment]
VR recording was not planned at the time of creating this plugin. You probably need to customize it to match your needs
